<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class InsertSamplePracticeQuestions extends Migration
{
    public function up()
    {
        // Check if questions already exist
        $existingCount = $this->db->table('practice_questions')->countAllResults();

        if ($existingCount > 0) {
            echo "Practice questions already exist ({$existingCount} found). Skipping insertion.\n";
            return;
        }

        // Get sample questions data
        $questions = $this->getSampleQuestionsData();

        // Insert all questions
        $this->db->table('practice_questions')->insertBatch($questions);

        echo "Successfully inserted " . count($questions) . " sample practice questions.\n";
    }

    public function down()
    {
        // Delete all sample practice questions
        $this->db->table('practice_questions')->truncate();
        echo "Removed all practice questions.\n";
    }

    private function getSampleQuestionsData()
    {
        $now = date('Y-m-d H:i:s');

        return [
            // English Language Questions (10)
            [
                'category' => 'English Language',
                'question_text' => 'Choose the correct synonym for "abundant".',
                'option_a' => 'Scarce',
                'option_b' => 'Plentiful',
                'option_c' => 'Limited',
                'option_d' => 'Rare',
                'correct_answer' => 'B',
                'explanation' => 'Abundant means existing in large quantities; plentiful.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Identify the part of speech of the underlined word: "She runs quickly."',
                'option_a' => 'Noun',
                'option_b' => 'Verb',
                'option_c' => 'Adverb',
                'option_d' => 'Adjective',
                'correct_answer' => 'C',
                'explanation' => 'Quickly is an adverb that modifies the verb "runs".',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Which sentence is grammatically correct?',
                'option_a' => 'Neither of the boys are coming.',
                'option_b' => 'Neither of the boys is coming.',
                'option_c' => 'Neither of the boys were coming.',
                'option_d' => 'Neither of the boys have coming.',
                'correct_answer' => 'B',
                'explanation' => 'Neither takes a singular verb form.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'What is the plural form of "child"?',
                'option_a' => 'Childs',
                'option_b' => 'Childes',
                'option_c' => 'Children',
                'option_d' => 'Childerns',
                'correct_answer' => 'C',
                'explanation' => 'Children is the irregular plural form of child.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Choose the correct form: "I have _____ finished my homework."',
                'option_a' => 'already',
                'option_b' => 'all ready',
                'option_c' => 'alredy',
                'option_d' => 'allready',
                'correct_answer' => 'A',
                'explanation' => 'Already means by this time or before now.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'What type of sentence is this: "What a beautiful day!"',
                'option_a' => 'Declarative',
                'option_b' => 'Interrogative',
                'option_c' => 'Exclamatory',
                'option_d' => 'Imperative',
                'correct_answer' => 'C',
                'explanation' => 'Exclamatory sentences express strong emotion and end with an exclamation mark.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Choose the antonym of "optimistic".',
                'option_a' => 'Hopeful',
                'option_b' => 'Positive',
                'option_c' => 'Pessimistic',
                'option_d' => 'Confident',
                'correct_answer' => 'C',
                'explanation' => 'Pessimistic is the opposite of optimistic.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Which word is spelled correctly?',
                'option_a' => 'Recieve',
                'option_b' => 'Receive',
                'option_c' => 'Receve',
                'option_d' => 'Receeve',
                'correct_answer' => 'B',
                'explanation' => 'The correct spelling follows the rule "i before e except after c".',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'What is the past tense of "go"?',
                'option_a' => 'Goed',
                'option_b' => 'Gone',
                'option_c' => 'Went',
                'option_d' => 'Going',
                'correct_answer' => 'C',
                'explanation' => 'Went is the past tense of the irregular verb "go".',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'English Language',
                'question_text' => 'Identify the figure of speech: "The stars danced in the sky."',
                'option_a' => 'Simile',
                'option_b' => 'Metaphor',
                'option_c' => 'Personification',
                'option_d' => 'Hyperbole',
                'correct_answer' => 'C',
                'explanation' => 'Personification gives human characteristics to non-human things.',
                'difficulty' => 'hard',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // Mathematics Questions (10)
            [
                'category' => 'Mathematics',
                'question_text' => 'What is 15% of 200?',
                'option_a' => '25',
                'option_b' => '30',
                'option_c' => '35',
                'option_d' => '40',
                'correct_answer' => 'B',
                'explanation' => '15% of 200 = (15/100) × 200 = 30',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'Solve for x: 2x + 5 = 15',
                'option_a' => '5',
                'option_b' => '10',
                'option_c' => '7.5',
                'option_d' => '20',
                'correct_answer' => 'A',
                'explanation' => '2x + 5 = 15, so 2x = 10, therefore x = 5',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'What is the area of a circle with radius 7 cm? (Use π = 22/7)',
                'option_a' => '154 cm²',
                'option_b' => '144 cm²',
                'option_c' => '164 cm²',
                'option_d' => '174 cm²',
                'correct_answer' => 'A',
                'explanation' => 'Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm²',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'What is the next number in the sequence: 2, 6, 18, 54, ?',
                'option_a' => '108',
                'option_b' => '162',
                'option_c' => '216',
                'option_d' => '324',
                'correct_answer' => 'B',
                'explanation' => 'Each number is multiplied by 3: 54 × 3 = 162',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'If a triangle has angles of 60° and 70°, what is the third angle?',
                'option_a' => '40°',
                'option_b' => '50°',
                'option_c' => '60°',
                'option_d' => '70°',
                'correct_answer' => 'B',
                'explanation' => 'Sum of angles in a triangle = 180°. Third angle = 180° - 60° - 70° = 50°',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'What is the square root of 144?',
                'option_a' => '11',
                'option_b' => '12',
                'option_c' => '13',
                'option_d' => '14',
                'correct_answer' => 'B',
                'explanation' => '√144 = 12 because 12² = 144',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'Convert 0.75 to a fraction in its simplest form.',
                'option_a' => '75/100',
                'option_b' => '3/4',
                'option_c' => '15/20',
                'option_d' => '6/8',
                'correct_answer' => 'B',
                'explanation' => '0.75 = 75/100 = 3/4 (simplified)',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'What is the volume of a cube with side length 4 cm?',
                'option_a' => '16 cm³',
                'option_b' => '48 cm³',
                'option_c' => '64 cm³',
                'option_d' => '96 cm³',
                'correct_answer' => 'C',
                'explanation' => 'Volume of cube = side³ = 4³ = 64 cm³',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'If 3x - 7 = 2x + 5, what is the value of x?',
                'option_a' => '10',
                'option_b' => '12',
                'option_c' => '15',
                'option_d' => '18',
                'correct_answer' => 'B',
                'explanation' => '3x - 7 = 2x + 5, so 3x - 2x = 5 + 7, therefore x = 12',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Mathematics',
                'question_text' => 'What is the probability of getting a head when flipping a fair coin?',
                'option_a' => '1/4',
                'option_b' => '1/3',
                'option_c' => '1/2',
                'option_d' => '2/3',
                'correct_answer' => 'C',
                'explanation' => 'A fair coin has 2 equally likely outcomes, so P(head) = 1/2',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // Civic Education Questions (10)
            [
                'category' => 'Civic Education',
                'question_text' => 'What is democracy?',
                'option_a' => 'Rule by the military',
                'option_b' => 'Government by the people',
                'option_c' => 'Rule by one person',
                'option_d' => 'Government by the wealthy',
                'correct_answer' => 'B',
                'explanation' => 'Democracy means government by the people, for the people.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'Which of these is a fundamental human right?',
                'option_a' => 'Right to education',
                'option_b' => 'Right to luxury',
                'option_c' => 'Right to rule others',
                'option_d' => 'Right to break laws',
                'correct_answer' => 'A',
                'explanation' => 'Education is recognized as a fundamental human right.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What is the highest court in Nigeria?',
                'option_a' => 'High Court',
                'option_b' => 'Court of Appeal',
                'option_c' => 'Supreme Court',
                'option_d' => 'Federal High Court',
                'correct_answer' => 'C',
                'explanation' => 'The Supreme Court is the highest court in Nigeria.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'How many arms of government are there?',
                'option_a' => 'Two',
                'option_b' => 'Three',
                'option_c' => 'Four',
                'option_d' => 'Five',
                'correct_answer' => 'B',
                'explanation' => 'There are three arms: Executive, Legislative, and Judicial.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What does the rule of law mean?',
                'option_a' => 'Laws are above everyone',
                'option_b' => 'Only lawyers make laws',
                'option_c' => 'Laws apply to everyone equally',
                'option_d' => 'Laws change daily',
                'correct_answer' => 'C',
                'explanation' => 'Rule of law means laws apply equally to all citizens.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What is citizenship?',
                'option_a' => 'Living in a city',
                'option_b' => 'Membership of a state',
                'option_c' => 'Being wealthy',
                'option_d' => 'Having a job',
                'correct_answer' => 'B',
                'explanation' => 'Citizenship is legal membership of a state or country.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'Which is a civic responsibility?',
                'option_a' => 'Paying taxes',
                'option_b' => 'Buying expensive cars',
                'option_c' => 'Traveling abroad',
                'option_d' => 'Owning property',
                'correct_answer' => 'A',
                'explanation' => 'Paying taxes is a civic duty of all citizens.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What is corruption?',
                'option_a' => 'Hard work',
                'option_b' => 'Dishonest conduct',
                'option_c' => 'Good leadership',
                'option_d' => 'Fair play',
                'correct_answer' => 'B',
                'explanation' => 'Corruption involves dishonest or fraudulent conduct.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What is the minimum voting age in Nigeria?',
                'option_a' => '16 years',
                'option_b' => '17 years',
                'option_c' => '18 years',
                'option_d' => '21 years',
                'correct_answer' => 'C',
                'explanation' => 'The minimum voting age in Nigeria is 18 years.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Civic Education',
                'question_text' => 'What does separation of powers mean?',
                'option_a' => 'Dividing government into branches',
                'option_b' => 'Separating rich from poor',
                'option_c' => 'Dividing the country',
                'option_d' => 'Separating religions',
                'correct_answer' => 'A',
                'explanation' => 'Separation of powers divides government into different branches.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // Current Affairs Questions (10)
            [
                'category' => 'Current Affairs',
                'question_text' => 'Who is the current President of Nigeria?',
                'option_a' => 'Muhammadu Buhari',
                'option_b' => 'Bola Ahmed Tinubu',
                'option_c' => 'Goodluck Jonathan',
                'option_d' => 'Olusegun Obasanjo',
                'correct_answer' => 'B',
                'explanation' => 'Bola Ahmed Tinubu is the current President of Nigeria (2023-present).',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'What is the capital of Nigeria?',
                'option_a' => 'Lagos',
                'option_b' => 'Kano',
                'option_c' => 'Abuja',
                'option_d' => 'Port Harcourt',
                'correct_answer' => 'C',
                'explanation' => 'Abuja is the capital city of Nigeria.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'Nigeria gained independence in which year?',
                'option_a' => '1958',
                'option_b' => '1960',
                'option_c' => '1962',
                'option_d' => '1963',
                'correct_answer' => 'B',
                'explanation' => 'Nigeria gained independence from Britain on October 1, 1960.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'How many states are in Nigeria?',
                'option_a' => '34',
                'option_b' => '35',
                'option_c' => '36',
                'option_d' => '37',
                'correct_answer' => 'C',
                'explanation' => 'Nigeria has 36 states and the Federal Capital Territory.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'What is the currency of Nigeria?',
                'option_a' => 'Dollar',
                'option_b' => 'Naira',
                'option_c' => 'Pound',
                'option_d' => 'Euro',
                'correct_answer' => 'B',
                'explanation' => 'The Nigerian Naira is the official currency of Nigeria.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'Which organization is Nigeria a member of?',
                'option_a' => 'ECOWAS',
                'option_b' => 'European Union',
                'option_c' => 'ASEAN',
                'option_d' => 'NATO',
                'correct_answer' => 'A',
                'explanation' => 'Nigeria is a founding member of ECOWAS (Economic Community of West African States).',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'What is the largest city in Nigeria by population?',
                'option_a' => 'Abuja',
                'option_b' => 'Kano',
                'option_c' => 'Lagos',
                'option_d' => 'Ibadan',
                'correct_answer' => 'C',
                'explanation' => 'Lagos is the largest city in Nigeria by population.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'Nigeria is located in which continent?',
                'option_a' => 'Asia',
                'option_b' => 'Africa',
                'option_c' => 'Europe',
                'option_d' => 'South America',
                'correct_answer' => 'B',
                'explanation' => 'Nigeria is located in West Africa.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'What is Nigeria\'s main export?',
                'option_a' => 'Cocoa',
                'option_b' => 'Oil',
                'option_c' => 'Gold',
                'option_d' => 'Cotton',
                'correct_answer' => 'B',
                'explanation' => 'Oil (petroleum) is Nigeria\'s main export commodity.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'Current Affairs',
                'question_text' => 'Which river is the longest in Nigeria?',
                'option_a' => 'River Benue',
                'option_b' => 'River Niger',
                'option_c' => 'River Kaduna',
                'option_d' => 'River Cross',
                'correct_answer' => 'B',
                'explanation' => 'River Niger is the longest river in Nigeria.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // French Questions (10)
            [
                'category' => 'French',
                'question_text' => 'How do you say "Hello" in French?',
                'option_a' => 'Au revoir',
                'option_b' => 'Bonjour',
                'option_c' => 'Merci',
                'option_d' => 'Bonsoir',
                'correct_answer' => 'B',
                'explanation' => 'Bonjour means "Hello" or "Good morning" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'What does "Merci" mean in English?',
                'option_a' => 'Hello',
                'option_b' => 'Goodbye',
                'option_c' => 'Thank you',
                'option_d' => 'Please',
                'correct_answer' => 'C',
                'explanation' => 'Merci means "Thank you" in English.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'How do you say "Yes" in French?',
                'option_a' => 'Non',
                'option_b' => 'Oui',
                'option_c' => 'Peut-être',
                'option_d' => 'Jamais',
                'correct_answer' => 'B',
                'explanation' => 'Oui means "Yes" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'What is "water" in French?',
                'option_a' => 'Lait',
                'option_b' => 'Jus',
                'option_c' => 'Eau',
                'option_d' => 'Vin',
                'correct_answer' => 'C',
                'explanation' => 'Eau means "water" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'How do you say "Good evening" in French?',
                'option_a' => 'Bonjour',
                'option_b' => 'Bonne nuit',
                'option_c' => 'Bonsoir',
                'option_d' => 'Bon après-midi',
                'correct_answer' => 'C',
                'explanation' => 'Bonsoir means "Good evening" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'What does "Je suis" mean?',
                'option_a' => 'I am',
                'option_b' => 'You are',
                'option_c' => 'He is',
                'option_d' => 'We are',
                'correct_answer' => 'A',
                'explanation' => 'Je suis means "I am" in English.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'How do you say "book" in French?',
                'option_a' => 'Stylo',
                'option_b' => 'Livre',
                'option_c' => 'Cahier',
                'option_d' => 'Papier',
                'correct_answer' => 'B',
                'explanation' => 'Livre means "book" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'What is "red" in French?',
                'option_a' => 'Bleu',
                'option_b' => 'Vert',
                'option_c' => 'Rouge',
                'option_d' => 'Jaune',
                'correct_answer' => 'C',
                'explanation' => 'Rouge means "red" in French.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'How do you say "My name is" in French?',
                'option_a' => 'Je suis',
                'option_b' => 'Je m\'appelle',
                'option_c' => 'Tu es',
                'option_d' => 'Il est',
                'correct_answer' => 'B',
                'explanation' => 'Je m\'appelle means "My name is" in French.',
                'difficulty' => 'medium',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'category' => 'French',
                'question_text' => 'What does "Au revoir" mean?',
                'option_a' => 'Hello',
                'option_b' => 'Thank you',
                'option_c' => 'Goodbye',
                'option_d' => 'Please',
                'correct_answer' => 'C',
                'explanation' => 'Au revoir means "Goodbye" in English.',
                'difficulty' => 'easy',
                'points' => 1,
                'is_active' => 1,
                'created_by' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ]
        ];
    }
}
